---
    - name: Configure PIM RP address   #OK.$ #Role9 - Role Name: pim_multicast &
      cisco.nxos.nxos_pim_rp_address:
        rp_address: "{{ pim_rp_ip }}"
        group_list: "{{ pim_mgroup }}"
      tags:
        - pim_multicast