---
    - name: Configure internal and external L2 Interfaces to Servers and Externals-No Port-Channel   #OK.$ (Role Name: configure_bl_local_segment_orphan)
      cisco.nxos.nxos_l2_interfaces:
        config:
          - name: "{{ item.intf_name }}"
            mode: "{{ item.switchport_mode }}"
            trunk:
              allowed_vlans: "{{ item.trunk_vlan }}"
              native_vlan: "{{ native_vlan_id }}" 
        state: merged
      with_items:
        - "{{ server_interfaces }}"
        - "{{ external_l2_interfaces }}"
      when: item.switchport_mode == 'trunk' and item.intf_po is not defined
      tags:
        - configure_l2_interfaces_trunk_nopo

    - name: Configure L2 Interfaces to Servers-No Port-Channel   #OK.$ (Role Name: configure_bl_local_segment_orphan)
      cisco.nxos.nxos_l2_interfaces:
        config:
          - name: "{{ item.intf_name }}"
            mode: "{{ item.switchport_mode }}"
            access:
              vlan: "{{ item.access_vlan }}"
        state: merged
      loop: "{{ server_interfaces }}"
      when: item.switchport_mode == 'access' and item.intf_po is not defined
      tags:
        - configure_l2_interfaces_access_nopo