# the variables for sic_leaf2

#OK.$ (sic_leaf2/rest.yaml)
hostname: sic_leaf2

#OK.$ (sic_leaf2/rest.yaml)
bgp_asn: 65203

#OK.$ (sic_leaf2/vpc.yaml)
vpc_domain: 2
vpc_pkl_dest: "100.120.23.201"

#OK.$ (sic_leaf2/sic_leaf2_underlay_intfs.yaml)
loopback_interfaces:
  - intf_name: Loopback0
    intf_ip: 10.0.0.203
    intf_subnet: 32
    intf_desc: LP0_RID
  - intf_name: Loopback1
    intf_ip: 10.3.0.203
    intf_subnet: 32
    intf_desc: LP1_NVE
    # ip_secondary: 10.2.2.2
    # sec_value: true

#OK.$ (sic_leaf2/sic_leaf2_underlay_intfs.yaml)
physical_interfaces:
  - intf_name: Ethernet1/1
    intf_desc: "To_Spine-1"
    intf_status: true
    intf_ip: 10.0.2.6
    intf_subnet: 30
    intf_mode: "layer3"
  - intf_name: Ethernet1/2
    intf_desc: "To_Spine-2"
    intf_status: true
    intf_ip: 10.0.2.134
    intf_subnet: 30
    intf_mode: "layer3"

#OK.$ (sic_leaf2/sic_leaf2_local_segment_intfs.yaml)
server_interfaces:
  - intf_name: Ethernet1/6
    intf_desc: "To_Subnet11-SRVs"
    intf_status: true
    switchport_mode: "access"
    access_vlan: 11
    intf_mode: "layer2"
    intf_po: 11
  - intf_name: Ethernet1/7
    intf_desc: "To_Subnet12-SRVs"
    intf_status: true
    switchport_mode: "access"
    access_vlan: 12
    intf_mode: "layer2"
    intf_po: 12