# NOT COMPLETE

# the variables for sic_bl

#OK.$ (sic_bl/rest.yaml)
hostname: sic_bl

#OK.$ (sic_bl/rest.yaml)
bgp_asn: 65211

#OK.$
# vpc_domain: 2
# vpc_pkl_dest: "100.120.23.211"

#OK.$ (sic_bl/sic_bl_underlay_intfs.yaml)
loopback_interfaces:
  - intf_name: Loopback0
    intf_ip: 10.0.0.211
    intf_subnet: 32
    intf_desc: LP0_RID
  - intf_name: Loopback1
    intf_ip: 10.3.0.211
    intf_subnet: 32
    intf_desc: LP1_NVE
    # ip_secondary: 10.2.2.2
    # sec_value: true

#OK.$ (sic_bl/sic_bl_underlay_intfs.yaml)
physical_interfaces:
  - intf_name: Ethernet1/1
    intf_desc: "To_Spine-1"
    intf_status: true
    intf_ip: 10.0.2.42
    intf_subnet: 30
    intf_mode: "layer3"
  - intf_name: Ethernet1/2
    intf_desc: "To_Spine-2"
    intf_status: true
    intf_ip: 10.0.2.170
    intf_subnet: 30
    intf_mode: "layer3"

#(sic_bl/sic_bl_external_connection.yaml)
external_l2_interfaces:
  - intf_name: Ethernet1/6
    intf_desc: "SIC-DC-L3FW-1-Port1"
    intf_status: true
    switchport_mode: "trunk"
    # intf_lag_mode: active
    trunk_vlan: 500,501
    intf_mode: "layer2"
    # intf_po: 13
  - intf_name: Ethernet1/7
    intf_desc: "SIC-DC-L3FW-2-Port1"
    intf_status: true
    switchport_mode: "trunk"
    # intf_lag_mode: active
    trunk_vlan: 500,501
    intf_mode: "layer2"
  # - intf_name: Ethernet1/8
  #   intf_desc: "SIC-External-L3FW-1"
  #   intf_status: true
  #   switchport_mode: "access"
  #   access_vlan: 500
  #   intf_mode: "layer2"
  #   # intf_po: 50
  # - intf_name: Ethernet1/9
  #   intf_desc: "SIC-External-L3FW-2"
  #   intf_status: true
  #   switchport_mode: "access"
  #   access_vlan: 500
  #   intf_mode: "layer2"
  #   # intf_po: 50

#(sic_bl/sic_bl_external_connection.yaml)
external_l3vlans:
  - vlan_id: 500
    vlan_name: "External-Tenant-1"
    vlan_id_ip: 10.0.4.253
    vlan_id_subnet: 30
    vrf_name: "Tenant-1"
    bgp_neighbor_addr_ext: 10.0.4.254
    bgp_update_src_ext: "VLAN500"
    bgp_peer_asn_ext: 65420
  - vlan_id: 501
    vlan_name: "External-Tenant-2"
    vlan_id_ip: 10.0.4.249
    vlan_id_subnet: 30
    vrf_name: "Tenant-2"
    bgp_neighbor_addr_ext: 10.0.4.250
    bgp_update_src_ext: "VLAN501"
    bgp_peer_asn_ext: 65410

#OK.$ #(sic_bl/sic_bl_local_segment.yaml)
server_interfaces:
  - intf_name: Ethernet1/6
    intf_desc: "To_Subnet11-SRVs"
    intf_status: true
    switchport_mode: "access"
    access_vlan: 11
    intf_mode: "layer2"
    intf_po: 11
  - intf_name: Ethernet1/7
    intf_desc: "To_Subnet12-SRVs"
    intf_status: true
    switchport_mode: "access"
    access_vlan: 12
    intf_mode: "layer2"
    intf_po: 12