---
- name: Enable necessary features   #OK.$
  cisco.nxos.nxos_feature:
    feature: "{{ item }}"
    state: enabled
  loop: "{{ features }}"
  tags:
    - enable_features
  
- name: Enable NV Overlay EVPN   #OK.$
  cisco.nxos.nxos_evpn_global:
    nv_overlay_evpn: true
  tags: evpn_feature