---
    - name: Ensure VLANs are configured   #OK.$
      cisco.nxos.nxos_vlans:
        config:
          - vlan_id: "{{ item.vlan_id }}"
            name: "{{ item.vlan_name }}"
            mapped_vni: "{{ item.vnid }}"
        state: merged
      with_items:
        - "{{ vrf_config }}"
      tags:
        - configure_tenant_l3vni

    - name: Ensure External VLANs are configured   #OK.$
      cisco.nxos.nxos_vlans:
        config:
          - vlan_id: "{{ item.vlan_id }}"
            name: "{{ item.vlan_name }}"
        state: merged
      with_items:
        - "{{ external_l3vlans }}"
      tags:
        - configure_Tenants_to_External

    - name: Configure VRFs   #OK.$
      cisco.nxos.nxos_vrf:
        aggregate:
          - name: "{{ item.vrf_name }}"
            vni: "{{ item.vnid }}"
            rd: "{{ item.vrf_rd }}"
      loop: "{{ vrf_config }}"
      tags:
        - configure_vrf

    - name: LEAF tenants_svi naming configuration   #OK.$
      cisco.nxos.nxos_interfaces:
        config:
          - name: "vlan{{ item.vlan_id }}"
            description: "{{ item.vlan_name }}"
            enabled: true
        state: merged
      with_items: 
        - "{{ vrf_config }}"
        - "{{ external_l3vlans }}"
      tags:
        - tenants_and_external_svi_naming

    - name: LEAF internal and external tenants_svi vrf membership configuration   #OK.$
      cisco.nxos.nxos_vrf_interface:
        interface: "vlan{{ item.vlan_id }}"
        vrf: "{{ item.vrf_name }}"
        state: present
      with_items: 
        - "{{ vrf_config }}"
        - "{{ external_l3vlans }}"
      tags:
        - tenant_vrf_mem

    - name: LEAF tenants_svi ip forward configuration   #OK.$
      cisco.nxos.nxos_interfaces:
        config:
          - name: "vlan{{ item.vlan_id }}"
            ip_forward: "{{ ipforward }}"
            enabled: true
        state: merged
      loop: "{{ vrf_config }}"
      tags:
        - tenant_ip_forward