---
    - name: Configure NTP   #OK.$
      cisco.nxos.nxos_ntp_global:
        config:
          servers:
            - server: "{{ item }}"
              vrf: "{{ ntp_vrf }}"
      loop: "{{ ntp_server }}"
      tags:
        - ntp_config