# the variables for external connection

external_l2_interfaces:
  - intf_name: Ethernet1/11
    intf_desc: "SIC-DC-L3FW-1-Port1"
    intf_status: true
    switchport_mode: "trunk"
    intf_lag_mode: active
    trunk_vlan: 500,501
    intf_mode: "layer2"
  - intf_name: Ethernet1/12
    intf_desc: "SIC-DC-L3FW-2-Port1"
    intf_status: true
    switchport_mode: "trunk"
    intf_lag_mode: active
    trunk_vlan: 500,501
    intf_mode: "layer2"
  - intf_name: Ethernet1/13
    intf_desc: "SIC-External-L3FW-1"
    intf_status: true
    switchport_mode: "access"
    access_vlan: 500
    intf_mode: "layer2"
    intf_po: 50
  - intf_name: Ethernet1/14
    intf_desc: "SIC-External-L3FW-2"
    intf_status: true
    switchport_mode: "access"
    access_vlan: 501
    intf_mode: "layer2"
    intf_po: 51
  - intf_name: Ethernet1/15
    intf_desc: "SIC-DC-L3FW-1-Port1"
    intf_status: true
    switchport_mode: "trunk"
    intf_lag_mode: active
    trunk_vlan: 500,501
    intf_mode: "layer2"
    intf_po: 60
  - intf_name: Ethernet1/16
    intf_desc: "SIC-DC-L3FW-2-Port1"
    intf_status: true
    switchport_mode: "trunk"
    intf_lag_mode: active
    trunk_vlan: 500,501
    intf_mode: "layer2"
    intf_po: 61

external_l3vlans:
  - vlan_id: 500
    vlan_name: "External-Tenant-1"
    vlan_id_ip: 10.0.4.245
    vlan_id_subnet: 30
    vrf_name: "Tenant-1"
    bgp_neighbor_addr_ext: 10.0.4.246
    bgp_update_src_ext: "VLAN500"
    bgp_peer_asn_ext: 65420
  - vlan_id: 501
    vlan_name: "External-Tenant-2"
    vlan_id_ip: 10.0.4.241
    vlan_id_subnet: 30
    vrf_name: "Tenant-2"
    bgp_neighbor_addr_ext: 10.0.4.242
    bgp_update_src_ext: "VLAN501"
    bgp_peer_asn_ext: 65420