#bmi_leafs.yaml
# /opt/dcf_iac_project/inventories/group_vars/bmi_leafs.yaml

ospf_site_area_id: 0.0.0.1

bgp:   #name should be changed / bind to spines loopback0 ip
  - bgp_neighbor_addr: 10.0.0.11
  - bgp_neighbor_addr: 10.0.0.12