# ADD COMMENT

#OK.$ (dcf/tacacs_aaa.yaml)
aaa_srv_grp: AAA_Servers

#OK.$ (dcf/tacacs_aaa.yaml)
tacacs_srv_host: "172.27.0.1"
tacacs_srv_key: key1

#OK.$ (dcf/dcf_configure_ospf.yaml)
ospf_pro_id: underlay
ospf_net_type: point-to-point

#OK.$ (dcf/configure_user.yaml)
device_user: "admin"
device_pass: "1qaz!QAZ"
user_role: "network-admin"

#OK.$ (dcf/rest.yaml)
ntp_server:
  - 192.168.95.96
  - 192.168.95.95

#OK.$ (dcf/rest.yaml)
ntp_vrf: "management"

#OK.$ (dcf/rest.yaml)
pim_rp_ip: "10.3.0.254"
pim_mgroup: "239.0.0.0/8"

#OK.$ (dcf/telemetry.yaml)
# telemetry_src_intf: "mgmt0" 
telemetry_src_vrf: "management"

#OK.$ (dcf/rest.yaml)
intf_mtu: 9216

#OK.$ (dcf/dcf_configure_ospf.yaml)
ospf_dci_area_id: 0.0.0.0 

#OK.$ (dcf/dcf_configure_bgp.yaml)
bgp_update_src: "loopback0"
ebgp_multihop: 2
peer_status: "false"
bgp_maximum_path: 10

#OK.$ (dcf/telemetry.yaml)
telemetry_destination_groups:
  - dst_grp_id: 1
    destination:
      - dst_grp_ip: 192.168.100.1
        dst_grp_port: 50001
        dst_grp_protocol: gRPC
        dst_grp_encoding: GPB
  - dst_grp_id: 2
    destination:
      - dst_grp_ip: 192.168.100.2
        dst_grp_port: 60001
        dst_grp_protocol: gRPC
        dst_grp_encoding: GPB

#OK.$ (dcf/telemetry.yaml)
telemetry_sensor_groups:
  - sns_grp_id: 1
    sns_grp_data_src: DME
    path:
      - sns_grp_path_name: sys/ch
        sns_grp_path_depth: unbounded

#OK.$ (dcf/telemetry.yaml)
telemetry_subscriptions:
  - sub_grp_id: 1
    dst_grp_id: 2
    sensor_group:
      - sns_grp_id: 1
        sub_interval: 1000