# ADD COMMENT

#OK.$ (leafs/features.yaml)
features:   
  - nv overlay
  - ospf
  - bgp
  - pim
  - interface-vlan
  - vn-segment-vlan-based
  - lacp
  - vpc
  - tacacs+

#OK.$ (leafs/rest.yaml)
anycast_gw_mac: "0000.0000.1111" 

#OK.$ (leafs/rest.yaml)
l2rd: "auto"
l2rt: "auto"

#OK.$ (leafs/rest.yaml)
anycast_gw_mac_status: true

#OK.$ (leafs/rest.yaml)
svi_status: true

#OK.$ (leafs/rest.yaml)
ipforward: true

#OK.$ (leafs/vpc.yaml)
vpc_po_id: 1
vpc_pl_sw_mode: trunk
vpc_po_mode: active
vpc_native_vlan: 3333
vpc_pl: true

#OK.$ (leafs/vpc.yaml)
vpc_pkl_src: mgmt0
vpc_delay_restore: 150
vpc_auto_recovery: 360

#OK.$ (leafs/vpc.yaml)
vpc_pl_po_members:
  - vpc_pl_mem: "1/3"
  - vpc_pl_mem: "1/4"

#CHECK (leafs/rest.yaml)
native_vlan_id: 222

#OK.$ (leafs/vlans.yaml)
l2vlans:
  - vlan_id: 11
    vlan_name: "Subnet-11"
    vnid: 1000011
    vrf_name: Tenant-1
    bgp_prefix: 192.168.11.0/24
  - vlan_id: 12
    vlan_name: "Subnet-12"
    vnid: 1000012
    vrf_name: Tenant-1
    bgp_prefix: 192.168.12.0/24
  - vlan_id: 13
    vlan_name: "Subnet-12"
    vnid: 1000013
    vrf_name: Tenant-2
    bgp_prefix: 192.168.13.0/24

#OK.$ (leafs/vlans.yaml)
l3vlans:
  - vlan_id: 11
    vlan_name: "Subnet-11"
    vnid: 1000011
    vrf_name: "Tenant-1"
    vlan_id_ip: 192.168.11.1
    vlan_id_subnet: 24
    bgp_prefix: 192.168.11.0/24
  - vlan_id: 12
    vlan_name: "Subnet-12"
    vnid: 1000012
    vrf_name: "Tenant-1"
    vlan_id_ip: 192.168.12.1
    vlan_id_subnet: 24
    bgp_prefix: 192.168.12.0/24
  - vlan_id: 13
    vlan_name: "Subnet-13"
    vnid: 1000013
    vrf_name: "Tenant-2"
    vlan_id_ip: 192.168.13.1
    vlan_id_subnet: 24
    bgp_prefix: 192.168.13.0/24

#OK.$ (leafs/vrfs.yaml)
vrf_config:
  - vrf_name: "Tenant-1"
    vlan_id: 200
    vlan_name: "Tenant-1"
    vnid: "1000200"
    vrf_rd: "auto"
    address_family: "ipv4"
    vrf_mcast_group: 239.0.0.1
  - vrf_name: "Tenant-2"
    vlan_id: 201
    vlan_name: "Tenant-2"
    vnid: "1000201"
    vrf_rd: "auto"
    address_family: "ipv4"
    vrf_mcast_group: 239.0.0.2

#OK.$ (leafs/nve.yaml)
nve_intf_name: nve1

#OK.$ (leafs/leafs_configure_bgp.yaml)
bgp_neighbor_template: "Leaf_Spine_Peering"

#OK.$ (leafs/nve.yaml)
nve_src_intf: Loopback1
nve_intf_status: false