---
    - name: Configure BGP templates   #OK.$ #Role4 - Role Name: configure_bgp_spine
      cisco.nxos.nxos_bgp_templates:
        config:
          as_number: "{{ bgp_asn }}"
          neighbor:
            - name: "{{ item.bgp_neighbor_template }}"
              update_source: "{{ bgp_update_src }}" 
              ebgp_multihop: "{{ ebgp_multihop }}"   
              address_family:          
                - afi: "ipv4"
                  safi: "unicast"
                  send_community: "extended"
                - afi: "l2vpn"
                  safi: "evpn"
                  send_community: "extended"
                  route_map:
                    outbound: "{{ bgp_route_map }}"
      loop: "{{ bgp }}"
      tags: configure_bgp_template

    - name: Configure BGP Process and Neighbors   #OK.$ #Role4 - Role Name: configure_bgp_spine
      cisco.nxos.nxos_bgp_global:
        config:
          as_number: "{{ bgp_asn }}"
          log_neighbor_changes: true
          router_id: "{{ loopback_interfaces | selectattr('intf_name', 'match', 'Loopback0') | map(attribute='intf_ip') | first}}"
          neighbors:
            - neighbor_address: "{{ item.neighbor_address }}"
              remote_as: "{{ item.bgp_peer_asn }}"
              inherit:
                peer: "{{ item.bgp_neighbor_template }}"
              shutdown: false
        state: merged
      loop: "{{ bgp }}"
      tags: configure_bgp_af

    - name: Configure BGP neighbor   #OK.$ #Role4 - Role Name: configure_bgp_spine
      cisco.nxos.nxos_bgp_neighbor_address_family:
        config:
          as_number: "{{ bgp_asn }}"
          neighbors:
            - neighbor_address: "{{ item.neighbor_address }}"
              address_family:
                - afi: l2vpn
                  safi: evpn
                  rewrite_evpn_rt_asn: true
        state: merged
      loop: "{{ bgp }}"
      tags: bgp_neighbor

    - name: Configure BGP route target   #OK.$ #Role4 - Role Name: configure_bgp_spine
      cisco.nxos.nxos_bgp_address_family:
        config:
          as_number: "{{ bgp_asn }}"
          address_family:
            - afi: l2vpn
              safi: evpn
              retain:
                route_target:
                  retain_all: true
        state: merged
      tags: bgp_route_target

    - name: Configure BGP Maximum Paths   #OK.$ #Role4 - Role Name: configure_bgp_spine
      cisco.nxos.nxos_bgp_address_family:
        config:
          as_number: "{{ bgp_asn }}"
          address_family:
            - afi: l2vpn
              safi: evpn
              maximum_paths:
                parallel_paths: "{{ bgp_maximum_path }}"
            - afi: ipv4
              safi: unicast
              maximum_paths:
                parallel_paths: "{{ bgp_maximum_path }}"
        state: merged
      tags: configure_bgp_max_path

    - name: Configure Route-Map   #OK.$ #Role4 - Role Name: configure_bgp_spine
      cisco.nxos.nxos_route_maps:
        config:
          - route_map: "{{ bgp_route_map }}"
            entries:
              - sequence: "{{ bgp_route_map_seq }}"
                action: "{{ bgp_route_map_action }}"
                set:
                  ip:
                    next_hop:
                      unchanged: true
        state: merged
      tags: configure_route_map