#OK.$
server_interfaces:
  - intf_name: Ethernet1/6
    intf_desc: "To_Subnet11-SRVs"
    intf_status: true
    switchport_mode: "access"
    intf_lag_mode: active
    access_vlan: 11
    intf_mode: "layer2"
    intf_po: 11
  - intf_name: Ethernet1/7
    intf_desc: "To_Subnet12-SRVs"
    intf_status: true
    switchport_mode: "access"
    intf_lag_mode: active
    access_vlan: 12
    intf_mode: "layer2"
    intf_po: 12
  - intf_name: Ethernet1/8
    intf_desc: "To_Subnet13-SRVs"
    intf_status: true
    switchport_mode: "trunk"
    intf_lag_mode: active
    trunk_vlan: 15-20
    intf_mode: "layer2"
    intf_po: 13
  - intf_name: Ethernet1/9
    intf_desc: "To_Subnet14-SRVs"
    intf_status: true
    switchport_mode: "trunk"
    trunk_vlan: 50
    intf_mode: "layer2"