---
    - name: Configure OSPF   #OK.$ #Role14 - Role Name: configure_ospf
      cisco.nxos.nxos_ospfv2:
        config:
          processes:
            - process_id: "{{ ospf_pro_id }}"
              router_id: "{{ loopback_interfaces | selectattr('intf_name', 'match', 'Loopback0') | map(attribute='intf_ip') | first }}"
      tags:
        - configure_ospf

    - name: Configure Interfaces, OSPF   #OK.$ #Role14 - Role Name: configure_ospf
      cisco.nxos.nxos_ospf_interfaces:
        config:
          - name: "{{ item.intf_name }}"
            address_family:
              - afi: ipv4
                network: "{{ ospf_net_type }}"
                processes:
                  - process_id: "{{ ospf_pro_id }}"
                    area:
                      area_id: "{{ ospf_site_area_id }}"
      with_items:
        - "{{ physical_interfaces }}"
        - "{{ loopback_interfaces }}"
      tags:
        - configure_ospf_ports