---
    - name: Configure LAG Interfaces   #OK.$ (Role Name: configure_bl_local_segment_lag)
      cisco.nxos.nxos_lag_interfaces:
        config:
          - name: "{{ item.intf_po }}"
            members:
              - member: "{{ item.intf_name }}"
                mode: "{{ item.intf_lag_mode }}"
        state: merged
      # loop: "{{ server_interfaces }}"
      when: item.intf_po is defined
      tags:
        - configure_lag_interfaces

    - name: Configure L2 Interfaces to Servers   #OK.$ (Role Name: configure_bl_local_segment_lag)
      cisco.nxos.nxos_l2_interfaces:
        config:
          - name: "port-channel{{ item.intf_po }}"
            mode: "{{ item.switchport_mode }}"
            access:
              vlan: "{{ item.access_vlan }}"
        state: merged
      # loop: "{{ server_interfaces }}"
      when: item.switchport_mode == 'access' and item.intf_po is defined
      tags:
        - configure_l2_interfaces_access

    - name: Configure L2 Interfaces to Servers   #OK.$ (Role Name: configure_bl_local_segment_lag)
      cisco.nxos.nxos_l2_interfaces:
        config:
          - name: "port-channel{{ item.intf_po }}"
            mode: "{{ item.switchport_mode }}"
            trunk:
              allowed_vlans: "{{ item.trunk_vlan }}"
              native_vlan: "{{ native_vlan_id }}"
        state: replaced
      # loop: "{{ server_interfaces }}"
      when: item.switchport_mode == 'trunk' and item.intf_po is defined 
      tags:
        - configure_l2_interfaces_trunk