---
    - name: Copy running config to startup config   #OK.$
      cisco.nxos.nxos_config:
        backup: no
        save_when: always
      tags: write

    - name: Confiuration Saving   #OK.$
      cisco.nxos.nxos_config:
        lines:
          - copy running-config startup-config
      tags: 
        - write