# the variables for local segment interfaces

#OK.$
server_interfaces:
  - intf_name: Ethernet1/10
    intf_desc: "To_Subnet11-SRVs"
    intf_status: true
    switchport_mode: "access"
    access_vlan: 11
    intf_mode: "layer2"
    intf_po: 11
  - intf_name: Ethernet1/11
    intf_desc: "To_Subnet12-SRVs"
    intf_status: true
    switchport_mode: "access"
    access_vlan: 12
    intf_mode: "layer2"
    intf_po: 12
  - intf_name: Ethernet1/22
    intf_desc: "To_Subnet11-SRVs"
    intf_status: true
    switchport_mode: "trunk"
    native_vlan_id: 3333
    intf_mode: "layer2"
    trunk_vlan: 12
    intf_po: 22