# the variables for underlay interfaces

#OK.$
loopback_interfaces:
  - intf_name: Loopback0
    intf_ip: 10.0.0.12
    intf_subnet: 32
    intf_desc: LP0_RID
  - intf_name: Loopback1
    intf_ip: 10.3.0.254
    intf_subnet: 32
    intf_desc: LP1_RP

#OK.$
physical_interfaces:
  - intf_name: Ethernet1/1
    intf_desc: "To_Leaf-1"
    intf_status: true
    intf_ip: 10.0.1.129
    intf_subnet: 30
    intf_mode: "layer3"
  - intf_name: Ethernet1/4
    intf_desc: "To_SIC_SuperSpine"
    intf_status: true
    intf_ip: 10.0.2.234
    intf_subnet: 30
    intf_mode: "layer3"
  - intf_name: Ethernet1/2
    intf_desc: "To_BorderLeaf"
    intf_status: true
    intf_ip: 10.0.1.169
    intf_subnet: 30
    intf_mode: "layer3"
  - intf_name: Ethernet1/3
    intf_desc: "To_BMI_SuperSpine"
    intf_status: true
    intf_ip: 10.0.1.250
    intf_subnet: 30
    intf_mode: "layer3"