---
    - name: Configure OSPF   #OK.$ #Role3 - Role Name: configure_ospf_spine
      cisco.nxos.nxos_ospfv2:
        config:
          processes:
            - process_id: "{{ ospf_pro_id }}"
              router_id: "{{ loopback_interfaces | selectattr('intf_name', 'match', 'Loopback0') | map(attribute='intf_ip') | first }}"
      tags:
        - configure_ospf

    # - name: Configure Interfaces, OSPF #OK.$ (PAY ATTENTION TO THE NEXT TWO TASKS, COMBINE THEM TO ONE; IMP)
    #   cisco.nxos.nxos_ospf_interfaces:
    #     config:
    #       - name: "{{ item.intf_name }}"
    #         address_family:
    #           - afi: ipv4
    #             network: "{{ ospf_net_type }}"
    #             processes:
    #               - process_id: "{{ ospf_pro_id }}"
    #                 area:
    #                   area_id: "{{ ospf_site_area_id }}"
    #   with_items:
    #     - "{{ physical_interfaces }}"
    #     - "{{ loopback_interfaces }}"
    #   tags:
    #     - configure_ospf_ports

    - name: Configure Interfaces, OSPF   #OK.$ (IMP) #Role3 - Role Name: configure_ospf_spine
      cisco.nxos.nxos_ospf_interfaces:
        config:
          - name: "{{ item.intf_name }}"
            address_family:
              - afi: ipv4
                network: "{{ ospf_net_type }}"
                processes:
                  - process_id: "{{ ospf_pro_id }}"
                    area:
                      area_id: "{{ ospf_site_area_id }}"
      loop: "{{ loopback_interfaces }}"
      tags:
        - configure_loopback_ospf_ports

    - name: Configure Interfaces, OSPF   #OK.$ (IMP) #Role3 - Role Name: configure_ospf_spine
      cisco.nxos.nxos_ospf_interfaces:
        config:
          - name: "{{ item.intf_name }}"
            address_family:
              - afi: ipv4
                network: "{{ ospf_net_type }}"
                processes:
                  - process_id: "{{ ospf_pro_id }}"
                    area:
                      area_id: "{{ ospf_site_area_id }}"
      loop: "{{ to_site_ospf_intf }}"
      tags:
        - configure_site_ospf_ports

    - name: Configure Interfaces, OSPF   #OK.$ (IMP) #Role3 - Role Name: configure_ospf_spine
      cisco.nxos.nxos_ospf_interfaces:
        config:
          - name: "{{ item.intf_name }}"
            address_family:
              - afi: ipv4
                network: "{{ ospf_net_type }}"
                processes:
                  - process_id: "{{ ospf_pro_id }}"
                    area:
                      area_id: "{{ ospf_dci_area_id }}"
      loop: "{{ to_dci_ospf_intf }}"
      tags:
        - configure_dci_ospf_ports