#BORDERLEAF PLAYBOOK
---
- name: Configure Cisco Nexus Switch - BorderLeaf
  hosts: border_leafs
  gather_facts: false
  connection: network_cli
  vars:
    ansible_network_os: cisco.nxos.nxos
  
  tasks:
    - import_role: #LOOP INSIDE
        name: configure_underlay_intfs

    - import_role: #LOOP INSIDE
        name: configure_ospf_leaf

    - import_role: #NO LOOP
        name: configure_anycast_gw

    - import_role: #NO LOOP
        name: configure_pim_multicast

    - include_role: #LOOP OUTSIDE
        name: configure_pim_ports
      with_items:
        - "{{ physical_interfaces }}"
        - "{{ loopback_interfaces }}"

    - import_role: #LOOP INSIDE
        name: configure_bgp_borderleaf

    - import_role: #LOOP INSIDE
        name: configure_nve_intf

    - import_role: #LOOP INSIDE
        name: configure_tenant_bl

    - import_role: #LOOP INSIDE
        name: configure_fabric_vlans_bl

    - include_role: #LOOP OUTSIDE
        name: configure_bl_local_segment_lag
      loop: "{{ server_interfaces }}"

    - import_role: #LOOP INSIDE
        name: configure_bl_local_segment_orphan

    - import_role: #NO LOOP
        name: write_bck