---
- name: Configure Cisco Nexus Switch - ALL - WITH ROLES
  hosts: leafs
  gather_facts: false
  connection: network_cli
  vars:
    ansible_network_os: cisco.nxos.nxos

  tasks:
    - import_role:
        name: configure_vpc

    - import_role:
        name: configure_underlay_intfs

    - import_role:
        name: configure_ospf

    - import_role:
        name: configure_anycast_gw

    - import_role:
        name: configure_pim_multicast

    - import_role:
        name: configure_pim_ports

    - import_role:
        name: configure_bgp_leaf

    - import_role:
        name: configure_tenant

    - import_role:
        name: configure_fabric_vlans

    - import_role:
        name: configure_nve_intf

    - import_role:
        name: configure_local_segment_lag

    - import_role:
        name: configure_local_segment_orphan

    - import_role:
        name: write_bck