---
- name: Configure Cisco Nexus Switch - LEAFS - WITH ROLES
  hosts: leafs
  gather_facts: false
  connection: network_cli
  vars:
    ansible_network_os: cisco.nxos.nxos

  tasks:
    # - import_role: #LOOP INSIDE
    #     name: configure_vpc

    - import_role: #LOOP INSIDE
        name: configure_underlay_intfs

    - import_role: #LOOP INSIDE
        name: configure_ospf_leaf

    - import_role: #NO LOOP
        name: configure_anycast_gw

    - import_role: #NO LOOP
        name: configure_pim_multicast

    - include_role: #LOOP OUTSIDE
        name: configure_pim_ports
      with_items:
        - "{{ physical_interfaces }}"
        - "{{ loopback_interfaces }}"

    - import_role: #LOOP INSIDE
        name: configure_bgp_leaf

    - include_role: #LOOP OUTSIDE
        name: configure_tenant
      loop: "{{ vrf_config }}"

    - import_role: #LOOP INSIDE
        name: configure_fabric_vlans

    - import_role: #LOOP INSIDE
        name: configure_nve_intf

    - include_role: #LOOP OUTSIDE
        name: configure_local_segment_lag
      loop: "{{ server_interfaces }}"
      tags:
        - configure_lag_interfaces
        
    - include_role: #LOOP OUTSIDE
        name: configure_local_segment_orphan
      loop: "{{ server_interfaces }}"

    - import_role: #NO LOOP
        name: write_bck
