---
- name: Configure Cisco Nexus Switch - SIC Spine
  hosts: superspines
  gather_facts: false
  connection: network_cli
  vars:
    ansible_network_os: cisco.nxos.nxos

  tasks:
  
    - name: Configure Loopback Interface Descriptions   #OK.$ #Role1 - Role Name: configure_underlay_intfs &
      cisco.nxos.nxos_interfaces:
        config:
          - name: "Loopback{{ item.intf_name }}"
            description: "{{ item.intf_desc }}"
            enabled: true
        state: merged
      loop: "{{ loopback_interfaces }}"
      tags:
        - configure_loopbacks

    - name: Configure IP for Loopback   #OK.$ #Role1 - Role Name: configure_underlay_intfs &
      cisco.nxos.nxos_l3_interfaces:
        config:
          - name: "{{ item.intf_name }}"
            ipv4:
              - address: "{{ item.intf_ip }}/{{ item.intf_subnet }}"
        state: merged
      loop: "{{ loopback_interfaces }}"
      tags:
        - configure_loopbacks_ip

    - name: Configure Physical Ethernet Ports   #OK.$ #Role1 - Role Name: configure_underlay_intfs &
      cisco.nxos.nxos_interfaces:
        config:
          - name: "{{ item.intf_name }}"
            description: "{{ item.intf_desc }}"
            enabled: "{{ item.intf_status }}"
            mode: "{{ item.intf_mode }}"
            mtu: "{{ intf_mtu }}"
        state: merged
      loop: "{{ physical_interfaces }}"
      tags:
        - configure_ports

    - name: Configure IP for Physical Ethernet Ports   #OK.$ #Role1 - Role Name: configure_underlay_intfs &
      cisco.nxos.nxos_l3_interfaces:
        config:
          - name: "{{ item.intf_name }}"
            ipv4:
              - address: "{{ item.intf_ip }}/{{ item.intf_subnet }}"
        state: merged
      loop: "{{ physical_interfaces }}"
      tags:
        - configure_physical_ports_ip  
  
    - name: Configure PIM RP address   #OK.$ #Role2 - Role Name: configure_pim_multicast &
      cisco.nxos.nxos_pim_rp_address:
        rp_address: "{{ pim_rp_ip }}"
        group_list: "{{ pim_mgroup }}"
      tags: 
        - pim_multicast

    - name: Configure Interfaces, PIM   #OK.$ #Role2 - Role Name: configure_pim_multicast &
      cisco.nxos.nxos_pim_interface:
        interface: "{{ item.intf_name }}"
        sparse: true
      with_items:
        - "{{ physical_interfaces }}"
        - "{{ loopback_interfaces }}"
      tags:
        - configure_pim_ports

    - name: Configure OSPF   #OK.$ #Role3 - Role Name: configure_ospf_superspine
      cisco.nxos.nxos_ospfv2:
        config:
          processes:
            - process_id: "{{ ospf_pro_id }}"
              router_id: "{{ loopback_interfaces | selectattr('intf_name', 'match', 'Loopback0') | map(attribute='intf_ip') | first }}"
      tags:
        - configure_ospf

    - name: Configure Interfaces, OSPF   #OK.$ (IMP) #Role3 - Role Name: configure_ospf_spine
      cisco.nxos.nxos_ospf_interfaces:
        config:
          - name: "{{ item.intf_name }}"
            address_family:
              - afi: ipv4
                network: "{{ ospf_net_type }}"
                processes:
                  - process_id: "{{ ospf_pro_id }}"
                    area:
                      area_id: "{{ ospf_dci_area_id }}"
      with_items:
        - "{{ physical_interfaces }}"
        - "{{ loopback_interfaces }}"
      tags:
        - configure_ospf_ports

    - name: Configure BGP templates   #OK.$ #Role4 - Role Name: configure_bgp_superspine
      cisco.nxos.nxos_bgp_templates:
        config:
          as_number: "{{ bgp_asn }}"
          neighbor:
            - name: "{{ item.bgp_neighbor_template }}"
              update_source: "{{ bgp_update_src }}" 
              ebgp_multihop: "{{ ebgp_multihop }}"   
              address_family:          
                - afi: "ipv4"
                  safi: "unicast"
                  send_community: "extended"
                - afi: "l2vpn"
                  safi: "evpn"
                  send_community: "extended"
                  route_map:
                    outbound: "{{ bgp_route_map }}"
      loop: "{{ bgp }}"
      tags: configure_bgp_template

    - name: Configure BGP Process and Neighbors   #OK.$ #Role4 - Role Name: configure_bgp_superspine
      cisco.nxos.nxos_bgp_global:
        config:
          as_number: "{{ bgp_asn }}"
          log_neighbor_changes: true
          router_id: "{{ loopback_interfaces | selectattr('intf_name', 'match', 'Loopback0') | map(attribute='intf_ip') | first}}"
          neighbors:
            - neighbor_address: "{{ item.neighbor_address }}"
              remote_as: "{{ item.bgp_peer_asn }}"
              inherit:
                peer: "{{ item.bgp_neighbor_template }}"
              shutdown: false
        state: merged
      loop: "{{ bgp }}"
      tags: configure_bgp_af

    - name: Configure BGP neighbor   #OK.$ #Role4 - Role Name: configure_bgp_superspine
      cisco.nxos.nxos_bgp_neighbor_address_family:
        config:
          as_number: "{{ bgp_asn }}"
          neighbors:
            - neighbor_address: "{{ item.neighbor_address }}"
              address_family:
                - afi: l2vpn
                  safi: evpn
                  rewrite_evpn_rt_asn: true
        state: merged
      loop: "{{ bgp }}"
      tags: bgp_neighbor

    - name: Configure bgp route target   #OK.$ #Role4 - Role Name: configure_bgp_superspine
      cisco.nxos.nxos_bgp_address_family:
        config:
          as_number: "{{ bgp_asn }}"
          address_family:
            - afi: l2vpn
              safi: evpn
              retain:
                route_target:
                  retain_all: true
        state: merged
      tags: bgp_route_target

    - name: Configure BGP Maximum Paths   #OK.$ #Role4 - Role Name: configure_bgp_superspine
      cisco.nxos.nxos_bgp_address_family:
        config:
          as_number: "{{ bgp_asn }}"
          address_family:
            - afi: l2vpn
              safi: evpn
              maximum_paths:
                parallel_paths: "{{ bgp_maximum_path }}"
            - afi: ipv4
              safi: unicast
              maximum_paths:
                parallel_paths: "{{ bgp_maximum_path }}"
        state: merged
      tags: configure_bgp_max_path

    - name: Configure Route-Map   #OK.$ #Role4 - Role Name: configure_bgp_superspine
      cisco.nxos.nxos_route_maps:
        config:
          - route_map: "{{ bgp_route_map }}"
            entries:
              - sequence: "{{ bgp_route_map_seq }}"
                action: "{{ bgp_route_map_action }}"
                set:
                  ip:
                    next_hop:
                      unchanged: true
        state: merged
      tags: configure_route_map

    - name: Copy running config to startup config   #OK.$ #AVAILABLE IN ALL-ROLES
      cisco.nxos.nxos_config:
        backup: no
        save_when: always
      tags: write

    # - name: Confiuration Saving   #OK.$ #AVAILABLE IN ALL-ROLES
    #   cisco.nxos.nxos_config:
    #     lines:
    #       - copy running-config startup-config
    #   tags: 
    #     - write