---
- name: VLAN Configuration for Leaf Switches
  hosts: leafs
  gather_facts: false
  connection: network_cli
  vars:
    ansible_network_os: cisco.nxos.nxos

  tasks:
    - import_role:
        name: vlan_management
        tasks_from: configure_vlans